# items/ItemBase.pyi
from typing import Any
from ..custom_types import ItemTypes


class ItemBase:
    _name: str
    _description: str
    _amount: int
    _price: float
    _weight: float
    _type: ItemTypes

    def __init__(self, name: str, description: str, amount: int, price: float, weight: float, _type: Any) -> None: ...
    @property
    def amount(self) -> int: ...
    @amount.setter
    def amount(self, value: int) -> None: ...
    @property
    def price(self) -> float: ...
    @price.setter
    def price(self, value: float) -> None: ...
    @property
    def weight(self) -> float: ...
    @weight.setter
    def weight(self, value: float) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: Any) -> bool: ...
    def __hash__(self) -> int: ...
