# characters/player/_Inventory.pyi
from typing import List, Any
from items._ItemBase import ItemBase

class Inventory:
    _inventory: List[ItemBase]

    def __init__(self) -> None: ...
    def add(self, item: ItemBase) -> None: ...
    def remove(self, item: ItemBase) -> None: ...
    def show(self) -> None: ...
    def count(self) -> int: ...
    def has_item(self, item: ItemBase) -> bool: ...
    def clear(self) -> None: ...
